//nop commerece Add to cart
//Ajit created
BeginTestCase "SearchProductsInNopCommerce"
RunWithNewResults TC_SearchProduct
EndTestCase "SearchProductsInNopCommerce"
log"====complete 1st test case"
log"====complete 2st test case"
Log"webhook"
Log"Poolscm"
Log"Poolscm2"
Log"Other users commit and jenkins built automatically in one minute"
BeginTestCase "AddToCart"
RunWithNewResults TC_AddToCart
EndTestCase "AddToCart"
