
//search product
CommonFunctions.connectWithRdp "192.168.1.106","Ideabytes@123"
CommonFunctions.OpenWebAppFromWindows "Chrome","http://nopcommerce.testplant.com/"
CommonFunctions.VerifyImage "Searchstore"
CommonFunctions.EnterTextWithImage"Searchstore","Camera"
CommonFunctions.clickElementWithImage "SEARCHButton"

ApplicationFunctions.PageDownToFoundImage "cameraImage","4", pageDown
CommonFunctions.VerifyImage "cameraImage"
closeBrowser
